# PostgreSQL versions 7.4 - 8.1
#
# Get the C bindings:
#   gem install postgres
# or use the pure-Ruby bindings on Windows:
#   gem install postgres-pr
development: &development
  adapter: postgresql
  database: exemplo01
  username: exemplo_user  
  password: 123mudar
  pool: 20
  wait_timeout: 300
  port: 5432
